services:
  backend:
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      APP_DOCUMENT_MAX_FILE_SIZE: 30MB
      APP_DOCUMENT_MAX_REQUEST_SIZE: 31MB
  frontend:
    ports:
      - "127.0.0.1:5173:80"
